import { defineConfig } from 'vitepress'

export default defineConfig({
  base: process.env.BASE || '/',
  title: '前端面试知识库',
  description: '体系化的前端面试准备资料，以真实大厂面试为标准',
  lang: 'zh-CN',
  lastUpdated: true,
  cleanUrls: true,

  // favicon 通过 transformHead 注入，确保 href 使用 VitePress
  // 已解析的 base（包括 --base CLI 覆盖），跨平台可靠
  transformHead({ siteData }) {
    return [
      ['link', { rel: 'icon', type: 'image/svg+xml', href: `${siteData.base}favicon.svg` }],
    ]
  },

  themeConfig: {
    nav: [
      { text: '首页', link: '/' },
      { text: '复习路线', link: '/roadmap' },
      { text: '写作规范', link: '/writing-rules' },
      { text: '更新日志', link: '/changelog' },
    ],

    sidebar: {
      '/JavaScript/': [
        { text: 'JavaScript 知识地图', link: '/JavaScript/' },
        { text: 'this', link: '/JavaScript/this' },
        { text: 'call / apply / bind', link: '/JavaScript/call-apply-bind' },
        { text: 'new', link: '/JavaScript/new' },
        { text: '闭包', link: '/JavaScript/closure' },
        { text: '原型链', link: '/JavaScript/prototype-chain' },
        { text: 'Promise', link: '/JavaScript/promise' },
        { text: 'Event Loop', link: '/JavaScript/event-loop' },
        { text: '类型转换', link: '/JavaScript/type-coercion' },
        { text: 'Set / Map / WeakMap', link: '/JavaScript/set-map-weakmap' },
        { text: 'async / await', link: '/JavaScript/async-await' },
        { text: '深拷贝', link: '/JavaScript/deep-clone' },
        { text: '防抖 / 节流', link: '/JavaScript/debounce-throttle' },
        { text: '生成器 / 迭代器', link: '/JavaScript/generator-iterator' },
        { text: 'Proxy / Reflect', link: '/JavaScript/proxy-reflect' },
        { text: 'ArrayBuffer / TypedArray', link: '/JavaScript/arraybuffer-typedarray' },
        { text: '跨 Realm 场景', link: '/JavaScript/cross-realm' },
      ],
      '/CSS/': [
        { text: 'CSS 知识地图', link: '/CSS/' },
        { text: '盒模型', link: '/CSS/box-model' },
        { text: '选择器优先级', link: '/CSS/specificity' },
        { text: 'CSS 继承性', link: '/CSS/inheritance' },
        { text: 'BFC', link: '/CSS/bfc' },
        { text: 'position 定位', link: '/CSS/position' },
        { text: '层叠上下文', link: '/CSS/stacking-context' },
        { text: 'Flexbox', link: '/CSS/flexbox' },
        { text: 'Grid', link: '/CSS/grid' },
        { text: '居中方案', link: '/CSS/center-layout' },
        { text: '三栏布局', link: '/CSS/three-column-layout' },
        { text: '响应式', link: '/CSS/responsive' },
        { text: 'rem / vw', link: '/CSS/rem-vw' },
        { text: '移动端 1px', link: '/CSS/mobile-1px' },
        { text: '文本溢出省略', link: '/CSS/text-overflow' },
        { text: 'transition vs animation', link: '/CSS/transition-animation' },
        { text: '伪类 vs 伪元素', link: '/CSS/pseudo' },
        { text: 'CSS 渲染性能', link: '/CSS/css-performance' },
        { text: 'CSS 变量', link: '/CSS/css-variables' },
        { text: 'BEM 命名', link: '/CSS/bem' },
        { text: 'CSS Modules / Scoped', link: '/CSS/css-modules-scoped' },
      ],
      '/HTML/': [
        { text: 'HTML 知识地图', link: '/HTML/' },
        { text: 'HTML5 语义化', link: '/HTML/html5-semantic' },
        { text: 'DOCTYPE / Meta', link: '/HTML/doctype-meta' },
        { text: 'defer / async', link: '/HTML/script-defer-async' },
        { text: '块级 / 行内元素', link: '/HTML/block-inline' },
        { text: 'src / href', link: '/HTML/src-href' },
        { text: '图片懒加载', link: '/HTML/lazy-loading' },
        { text: 'SEO / SSR', link: '/HTML/seo-ssr' },
      ],
      '/Git/': [
        { text: 'Git 知识地图', link: '/Git/' },
        { text: 'Commit 规范', link: '/Git/commit-spec' },
        { text: 'merge vs rebase', link: '/Git/merge-vs-rebase' },
        { text: '冲突处理', link: '/Git/conflict-resolution' },
        { text: 'cherry-pick', link: '/Git/cherry-pick' },
        { text: 'stash', link: '/Git/stash' },
        { text: 'tag', link: '/Git/tag' },
        { text: 'reset vs revert', link: '/Git/reset-vs-revert' },
        { text: 'bisect', link: '/Git/bisect' },
        { text: 'Git Flow', link: '/Git/git-flow' },
      ],
      '/TypeScript/': [
        { text: 'TypeScript 知识地图', link: '/TypeScript/' },
        { text: '泛型', link: '/TypeScript/generics' },
        { text: 'extends / infer', link: '/TypeScript/extends-infer' },
        { text: 'keyof / mapped / conditional', link: '/TypeScript/keyof-mapped-conditional' },
        { text: 'Utility Types', link: '/TypeScript/utility-types' },
        { text: 'satisfies', link: '/TypeScript/satisfies' },
        { text: 'any / unknown / never', link: '/TypeScript/any-unknown-never' },
        { text: '声明文件 / declare', link: '/TypeScript/declaration' },
      ],
      '/Vue3/': [
        { text: 'Vue3 知识地图', link: '/Vue3/' },
        { text: '响应式原理', link: '/Vue3/reactivity' },
        { text: 'computed / watch', link: '/Vue3/computed-watch' },
        { text: 'nextTick', link: '/Vue3/nextTick' },
        { text: '生命周期', link: '/Vue3/lifecycle' },
        { text: 'Diff / Patch', link: '/Vue3/diff-patch' },
        { text: 'KeepAlive', link: '/Vue3/keepalive' },
        { text: 'Teleport / Suspense', link: '/Vue3/teleport-suspense' },
        { text: 'Composition API', link: '/Vue3/composition-api' },
        { text: 'v-model', link: '/Vue3/v-model' },
        { text: '组件通信', link: '/Vue3/component-communication' },
        { text: 'Renderer', link: '/Vue3/renderer' },
        { text: 'Scheduler', link: '/Vue3/scheduler' },
      ],
      '/VueRouter/': [
        { text: 'Vue Router 知识地图', link: '/VueRouter/' },
        { text: 'history / hash', link: '/VueRouter/history-vs-hash' },
        { text: '动态路由', link: '/VueRouter/dynamic-routing' },
        { text: '路由守卫', link: '/VueRouter/route-guards' },
        { text: 'KeepAlive 集成', link: '/VueRouter/keepalive-integration' },
        { text: 'scrollBehavior', link: '/VueRouter/scroll-behavior' },
        { text: '路由懒加载', link: '/VueRouter/lazy-loading' },
        { text: '导航故障处理', link: '/VueRouter/navigation-failures' },
      ],
      '/Pinia/': [
        { text: 'Pinia 知识地图', link: '/Pinia/' },
        { text: 'defineStore', link: '/Pinia/defineStore' },
        { text: 'state', link: '/Pinia/state' },
        { text: 'getters', link: '/Pinia/getters' },
        { text: 'actions', link: '/Pinia/actions' },
        { text: '持久化', link: '/Pinia/persist' },
        { text: 'vs Vuex', link: '/Pinia/vs-vuex' },
        { text: '插件', link: '/Pinia/plugins' },
      ],
      '/浏览器/': [
        { text: '浏览器 知识地图', link: '/浏览器/' },
        { text: 'URL 到页面展示', link: '/浏览器/url-to-page' },
        { text: '多进程架构', link: '/浏览器/browser-architecture' },
        { text: '渲染流程', link: '/浏览器/render-process' },
        { text: '重绘 / 回流', link: '/浏览器/reflow-repaint' },
        { text: '浏览器缓存', link: '/浏览器/cache' },
        { text: 'Web Storage', link: '/浏览器/storage' },
        { text: 'Web Worker', link: '/浏览器/web-worker' },
        { text: 'Service Worker', link: '/浏览器/service-worker' },
        { text: 'requestAnimationFrame', link: '/浏览器/request-animation-frame' },
        { text: '垃圾回收 GC', link: '/浏览器/gc' },
        { text: 'IndexedDB', link: '/浏览器/indexeddb' },
        { text: 'DOM 事件机制 / 事件委托', link: '/浏览器/dom-event-delegation' },
      ],
      '/网络/': [
        { text: '网络 知识地图', link: '/网络/' },
        { text: 'HTTP / HTTPS', link: '/网络/http-https' },
        { text: 'HTTP2 / HTTP3', link: '/网络/http2-http3' },
        { text: 'TCP', link: '/网络/tcp' },
        { text: 'DNS / CDN', link: '/网络/dns-cdn' },
        { text: 'WebSocket / SSE', link: '/网络/websocket-sse' },
        { text: 'CORS', link: '/网络/cors' },
      ],
      '/工程化/': [
        { text: '工程化 知识地图', link: '/工程化/' },
        { text: 'npm 深入', link: '/工程化/npm-deep' },
        { text: 'Vite', link: '/工程化/vite' },
        { text: 'Webpack', link: '/工程化/webpack' },
        { text: 'Babel / ESBuild', link: '/工程化/babel-esbuild' },
        { text: 'Tree Shaking', link: '/工程化/tree-shaking' },
        { text: 'pnpm', link: '/工程化/pnpm' },
        { text: 'Vite 深入', link: '/工程化/vite-deep' },
        { text: 'ESM 模块化', link: '/工程化/esm-module' },
        { text: 'Tailwind CSS', link: '/工程化/tailwindcss' },
      ],
      '/Node/': [
        { text: 'Node 知识地图', link: '/Node/' },
        { text: 'CommonJS / ESM', link: '/Node/commonjs-esm' },
        { text: 'Node Event Loop', link: '/Node/node-event-loop' },
        { text: 'npm / pnpm', link: '/Node/package-manager' },
        { text: 'Express / Koa', link: '/Node/express-koa' },
      ],
      '/算法/': [
        { text: '算法 知识地图', link: '/算法/' },
        { text: '数组', link: '/算法/array' },
        { text: '树', link: '/算法/tree' },
        { text: '链表', link: '/算法/linked-list' },
        { text: '栈和队列', link: '/算法/stack-queue' },
        { text: '排序', link: '/算法/sort' },
        { text: '高频题', link: '/算法/common-questions' },
        { text: '哈希表', link: '/算法/hash' },
        { text: '双指针', link: '/算法/two-pointers' },
        { text: '滑动窗口', link: '/算法/sliding-window' },
        { text: 'DFS / BFS', link: '/算法/dfs-bfs' },
        { text: '动态规划', link: '/算法/dynamic-programming' },
        { text: '二分查找', link: '/算法/binary-search' },
      ],
      '/安全/': [
        { text: '安全 知识地图', link: '/安全/' },
        { text: 'XSS', link: '/安全/xss' },
        { text: 'CSRF', link: '/安全/csrf' },
        { text: 'CSP', link: '/安全/csp' },
        { text: 'Token 存储安全', link: '/安全/token-storage' },
      ],
      '/性能优化/': [
        { text: '性能优化 知识地图', link: '/性能优化/' },
        { text: 'Web Vitals', link: '/性能优化/web-vitals' },
        { text: '首屏优化', link: '/性能优化/first-screen' },
        { text: '打包优化', link: '/性能优化/bundle-optimization' },
        { text: '虚拟列表', link: '/性能优化/virtual-list' },
        { text: '图片优化', link: '/性能优化/image-optimization' },
        { text: '性能分析工具', link: '/性能优化/performance-devtools' },
      ],
      '/前端架构/': [
        { text: '前端架构 知识地图', link: '/前端架构/' },
        { text: '项目分层设计', link: '/前端架构/project-structure' },
        { text: '模块解耦', link: '/前端架构/module-decoupling' },
        { text: '组件设计', link: '/前端架构/component-design' },
        { text: '设计模式', link: '/前端架构/design-patterns' },
        { text: 'Monorepo', link: '/前端架构/monorepo' },
      ],
      '/微前端/': [
        { text: '微前端 知识地图', link: '/微前端/' },
        { text: '微前端概述', link: '/微前端/overview' },
        { text: 'qiankun', link: '/微前端/qiankun' },
        { text: 'Module Federation', link: '/微前端/module-federation' },
        { text: 'iframe 方案', link: '/微前端/iframe' },
      ],
      '/CICD/': [
        { text: 'CI/CD 知识地图', link: '/CICD/' },
        { text: 'CI/CD 概述', link: '/CICD/overview' },
        { text: 'GitHub Actions', link: '/CICD/github-actions' },
        { text: 'Jenkins', link: '/CICD/jenkins' },
        { text: 'Docker', link: '/CICD/docker' },
      ],
      '/日志监控/': [
        { text: '日志监控 知识地图', link: '/日志监控/' },
        { text: 'Sentry', link: '/日志监控/sentry' },
        { text: '性能监控', link: '/日志监控/performance-monitor' },
        { text: '埋点系统', link: '/日志监控/tracking' },
        { text: '线上问题定位', link: '/日志监控/online-debug' },
      ],
      '/项目实战/': [
        { text: '项目实战 知识地图', link: '/项目实战/' },
        {
          text: '基础设施',
          link: '/项目实战/基础设施/axios-encapsulation',
          collapsed: false,
          items: [
            { text: 'Axios 封装', link: '/项目实战/基础设施/axios-encapsulation' },
            { text: '防重复请求', link: '/项目实战/基础设施/request-dedup' },
            { text: 'Mock', link: '/项目实战/基础设施/mock' },
          ],
        },
        {
          text: '认证鉴权',
          link: '/项目实战/认证鉴权/login-auth',
          collapsed: false,
          items: [
            { text: '登录鉴权', link: '/项目实战/认证鉴权/login-auth' },
            { text: 'Token 刷新', link: '/项目实战/认证鉴权/token-refresh' },
          ],
        },
        {
          text: '权限系统',
          link: '/项目实战/权限系统/dynamic-route',
          collapsed: false,
          items: [
            { text: '动态路由', link: '/项目实战/权限系统/dynamic-route' },
            { text: '权限 RBAC', link: '/项目实战/权限系统/permission-rbac' },
          ],
        },
        {
          text: '业务场景',
          link: '/项目实战/业务场景/file-upload',
          collapsed: false,
          items: [
            { text: '文件上传', link: '/项目实战/业务场景/file-upload' },
            { text: 'Excel 导入导出', link: '/项目实战/业务场景/excel-import-export' },
            { text: '大数据表格', link: '/项目实战/业务场景/big-data-table' },
            { text: '国际化', link: '/项目实战/业务场景/i18n' },
            { text: '主题切换', link: '/项目实战/业务场景/theme-switch' },
            { text: '组件封装实践', link: '/项目实战/业务场景/component-encapsulation' },
            { text: 'WebSocket 实战', link: '/项目实战/业务场景/websocket' },
            { text: 'ECharts 实战', link: '/项目实战/业务场景/echarts' },
            { text: '大文件上传', link: '/项目实战/业务场景/big-file-upload' },
            { text: 'Composable 设计', link: '/项目实战/业务场景/composable-design' },
          ],
        },
        { text: '项目优化', link: '/项目实战/项目优化/project-optimization' },
      ],
      '/手写题/': [
        { text: '手写题 知识地图', link: '/手写题/' },
        { text: 'Promise', link: '/手写题/promise' },
        { text: 'bind / call / apply', link: '/手写题/bind-call-apply' },
        { text: 'new', link: '/手写题/new' },
        { text: 'debounce / throttle', link: '/手写题/debounce-throttle' },
        { text: '深拷贝', link: '/手写题/deep-clone' },
        { text: 'EventEmitter', link: '/手写题/event-emitter' },
        { text: 'compose / pipe', link: '/手写题/compose-pipe' },
      ],
      '/面试题库/': [
        { text: '面试题库 总览', link: '/面试题库/' },
        { text: 'CSS', link: '/面试题库/CSS' },
        { text: 'JavaScript', link: '/面试题库/JavaScript' },
        { text: 'Vue3', link: '/面试题库/Vue3' },
        { text: 'TypeScript', link: '/面试题库/TypeScript' },
        { text: '浏览器', link: '/面试题库/浏览器' },
        { text: '网络', link: '/面试题库/网络' },
        { text: '工程化', link: '/面试题库/工程化' },
        { text: '项目', link: '/面试题库/项目' },
        { text: 'HR', link: '/面试题库/HR' },
      ],
      '/HR/': [
        { text: 'HR 面试地图', link: '/HR/' },
        { text: '自我介绍', link: '/HR/self-intro' },
        { text: '项目介绍', link: '/HR/project-intro' },
        { text: '离职原因', link: '/HR/leave-reason' },
        { text: '优缺点', link: '/HR/strength-weakness' },
        { text: '职业规划', link: '/HR/career-plan' },
      ],
      '/模拟面试/': [
        { text: '模拟面试 总览', link: '/模拟面试/' },
        { text: '一面：JS 基础', link: '/模拟面试/round-1-js' },
        { text: '一面：Vue 框架', link: '/模拟面试/round-1-vue' },
        { text: '二面：项目经验', link: '/模拟面试/round-2-project' },
        { text: '三面：HR', link: '/模拟面试/round-3-hr' },
      ],
      '/面试回答/': [
        { text: '面试回答 总览', link: '/面试回答/' },
        { text: 'JavaScript', link: '/面试回答/JavaScript/promise' },
        { text: 'Vue3', link: '/面试回答/Vue3/reactivity' },
        { text: '项目', link: '/面试回答/项目/login-auth' },
      ],
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com' },
    ],

    search: {
      provider: 'local',
      options: {
        translations: {
          button: {
            buttonText: '搜索文档',
            buttonAriaLabel: '搜索文档',
          },
          modal: {
            displayDetails: '显示详情',
            resetButtonTitle: '重置',
            backButtonTitle: '返回',
            noResultsText: '无结果',
            footer: {
              selectText: '选择',
              selectKeyAriaLabel: 'Enter',
              navigateText: '切换',
              navigateUpKeyAriaLabel: '上箭头',
              navigateDownKeyAriaLabel: '下箭头',
              closeText: '关闭',
              closeKeyAriaLabel: 'Esc',
            },
          },
        },
      },
    },

    outline: {
      level: [2, 3],
      label: '页面导航',
    },

    docFooter: {
      prev: '上一篇',
      next: '下一篇',
    },

    lastUpdated: {
      text: '最后更新',
    },
  },

  markdown: {
    lineNumbers: true,
  },

  vite: {
    optimizeDeps: {
      // mermaid 内部对每种图表类型做动态 import()，
      // Vite 预构建时会拆成独立 chunk。chunk hash 变化后
      // 缓存引用不同步导致 504。排除预构建让动态 import 原生运行。
      exclude: ['mermaid'],
    },
  },
})
